name: 更新ADX数据

on:
  schedule:
    # 每小时的第5分钟执行 (UTC时间，需要转换为北京时间)
    # 北京时间比UTC快8小时，所以这里的时间是UTC时间
    - cron: '5 * * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz
        
    - name: 拉取并处理数据
      env:
        API_USERNAME: ${{ secrets.API_USERNAME }}
        API_PASSWORD: ${{ secrets.API_PASSWORD }}
      run: |
        python .github/workflows/update_data.py
        
    - name: 提交更新的数据
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/data/
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "自动更新ADX数据 - $(date '+%Y-%m-%d %H:%M:%S')"
          git push
        else
          echo "没有数据需要更新"
        fi